[book]
authors = ["Shawn Tabrizi"]
language = "en"
multilingual = false
src = "src"
title = "Gitorial mdBook Template"

[output.html]
additional-css = ["custom/styles.css"]
additional-js = ["custom/tabs.js"]
git-repository-url = "https://github.com/gitorial-sdk/mdbook-template"
git-repository-icon = "fa-github"
